[package]
name = "art_peace"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.20.0" }
starknet = "2.6.3"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
casm = true
sierra = true
